### ISSUE TITLE
Generate more samples (python) and adapt the script

### ISSUE THREAD

**Issue by CarlosLopezElorduy** [bbglab/cancer-detective-pro#27]
Identify how samples are encoded and see which ones are hardcoded and which ones are truly random.

**Comment by clarnedp** [comment]
**Hardcoded data**

Files implicated: 
www/data/js/quiz.js
www/data/js/gens.js
www/data/js/analysis-slider.js

Things that I understand from some testings:
 
- Sample characteristics (type of cancer, age, risk factor 1 and risk factor 2) are truly random. You can find them in quiz.js lines 1-9. 

- The combination of mutations in each sample, however, is not random and is are hardcoded in gens.js. Each variable (var muta_a_1a_2a_3a... is a concatenation of a list of mutations. Each mutation has 4 different items (gen1, gen2, gen3, gen4; do not misunderstand these as genes!). Each of these items corresponds to a row in the mutations card: gen1 is Gen, gen2 is Canvi a la proteina, gen3 is Mutacio and gen4 is Tractament. You will find in quiz.js how each of the items are turned "active" as you progress through the slides (for example: w3.addClass('.gen2','active');). I don't understand yet where is the info of a mutation being driver (gen3) and the treatment (gen4) encoded. In summary, a given sample is always assigned to the same mutations. There are 27 possible combinations of mutations per cancer type. 

- Driver mutations are also hardcoded in www/data/js/analysis-slider.js line 31. I think this checks if mutations in each sample are included in the hardcoded list of driver mutations. Then computes which sample has more driver mutations or if they are equal. 

Next steps I'd like to work on (wk 13th May): 1) understand how all info is encoded, 2) Review drivers, passengers and treatments, 3) Add more combinations?

**Comment by CarlosLopezElorduy** [comment]
Actions:

- [ ] Create a python script that generates more hardcoded samples in the `gens.js`, following the same structure.
- [ ] Change the js code bellow to accept the new samples

https://github.com/bbglab/cancer-detective-pro/blob/d4a3fa64712331ac19a3be26fa36ca4ac4334af5/www/data/js/quiz.js#L1-L13

**Comment by CarlosLopezElorduy** [comment]
While working on my issue, I merged your changes into my branch and found a bug. Maybe due to the new generation of driver mutations, the question of which sample has more driver mutations is now broken:

![Image](https://github.com/user-attachments/assets/9d7ad1cb-0e4e-4388-a24b-fce5c3acad09)
![Image](https://github.com/user-attachments/assets/4d85442e-9bf9-41ae-821b-4dfd01308f91)
![Image](https://github.com/user-attachments/assets/74b1749c-ca17-4191-a051-34a8761d302a)

**Comment by clarnedp** [comment]
Do you know how is the answer encoded? What is the code "reading" to tell if it's patient 1, patient 2 or both are the same?

**Comment by CarlosLopezElorduy** [comment]
I think it is in this function:

https://github.com/bbglab/cancer-detective-pro/blob/15b176cc10293ba20509c0d098b0337b75a3aa59/www/data/js/analysis-slider.js#L29-L44

The idea is that it has hardcoded the driver mutations, so if you generated new ones, I'm guessing this list should be expanded with the new ones.

**Comment by clarnedp** [comment]
I've created a new "driver string" in line 31, but it's still not working. All changes are in the branch. I'm not sure what should we test now, I have the feeling that the if/else statements aren't working properly.

**Comment by CarlosLopezElorduy** [comment]
It is working 😄
